About us
Z-Ramezani/BOOM pull request #19
Opened 2022-05-22 11:03 UTC by Z-Ramezani

check the About us page 
figure out how to fix the tag section which I commented....

2022-05-25 20:04 UTC, Madanian requested changes
I review this. check my comments

2022-05-26 04:59 UTC, Shafizadegan commented on front/se_project/src/Pages/admin.jsx
> +                        <ShowArtworkAdCost />
why does it change?

2022-05-26 04:59 UTC, Shafizadegan commented on front/se_project/src/Pages/artistSignUp.jsx
> +export default ArtistSignUp;
why does it change?

2022-05-26 04:59 UTC, Shafizadegan commented on front/se_project/src/Pages/login.jsx
>  export default Login;
I don not underestand changing

2022-05-26 04:59 UTC, Shafizadegan commented on front/se_project/src/components/ArtworkAdInfo/showArtworkAdCost.jsx
> +
why does this page change?

2022-05-26 04:59 UTC, Shafizadegan commented on front/se_project/src/components/Footer/footer.jsx
> +
علت تغییر این صفحه چی بوده؟

2022-05-26 04:59 UTC, Shafizadegan commented on front/se_project/src/index.js
>  root.render(<App/>);
why?

2022-05-26 08:43 UTC, Z-Ramezani commented on front/se_project/src/Pages/admin.jsx
> +                        <ShowArtworkAdCost />
do this after merge.

2022-05-26 08:43 UTC, Z-Ramezani commented on front/se_project/src/Pages/aboutUs.jsx
> +                هرکاری میکنم خروجی ندارم  :| */}
fix it :)

2022-05-26 08:43 UTC, Z-Ramezani commented on front/se_project/src/App.js
> +
done!

2022-05-26 08:44 UTC, Z-Ramezani commented on front/se_project/src/Pages/aboutUs.jsx
> +                    <h6><strong className='me-2' style={{fontSize:'1.1vw',color:'#CC3737'}}>وقتی به بوم می‌پیوندید، به بازار هنر می‌پیوندید – دنیایی برای هنرمندان مستقل.</strong></h6>
gets better..

2022-05-26 08:55 UTC, Z-Ramezani commented on front/se_project/src/components/header-slide.jsx
>  export default HeaderSlide;
done!

2022-05-26 08:55 UTC, Z-Ramezani commented on front/se_project/src/components/horizontalLine/horizontalLine.jsx
>  export default HorizontalLine;
done!

2022-05-26 08:55 UTC, Z-Ramezani commented on front/se_project/src/components/navBar/navLink.jsx
>  export default NavLink;
done!

2022-05-26 08:56 UTC, Z-Ramezani commented on front/se_project/src/components/userInformation.jsx
> +    };
its ms.shafizadegan codes, not mine.

2022-05-26 08:57 UTC, Z-Ramezani commented on front/se_project/src/index.js
>  root.render(<App/>);
because we don't need them.

2022-05-26 20:08 UTC, aliinarimanii reviewed
بررسی شد.

2022-05-27 06:52 UTC, merged